In [1]:
import pandas as pd
from io import StringIO

# üìÇ Abrindo os CSVs importados da internet

In [2]:
df = pd.read_csv("../datasets/dados_abertos_rios___limpos(1).csv", sep=';')

In [3]:
df2 = pd.read_csv("../datasets/cnuc_2022_01sem.csv", encoding_errors='ignore', on_bad_lines='skip', sep=';')

# üß©  Selecionando as colunas que ser√£o utilizadas na an√°lise

In [4]:
df = df[
    [
        # Informa√ß√µes gerais
        "Data do mutir√£o",
        "Hor√°rio de in√≠cio",
        "Ambiente ",
        "Estado",
        "Cidade",
        "Nome do local (exemplo: praia de boa viagem)",
        "Bairro ou distrito",
        "Institui√ß√£o Organizadora",
        "Car√°ter da institui√ß√£o",
        "N√∫mero aproximado de participantes (total)",
        "Dura√ß√£o total (coleta + triagem)",
        "Peso total dos res√≠duos (kg)",
        "Quantidade total de itens coletados",

        # Pl√°stico
        "Pl√°stico (total)",
        "1. Fragmentos de pl√°stico (maiores que 2,5 cm).",
        "2. Brinquedos",
        "3. Canudos",
        "4. Copos/talheres/pratos",
        "5. Embalagens de alimento",
        "6. Escovas de dente",
        "7. Esponjas/espumas",
        "8. Gal√µes",
        "9. Garrafas PET",
        "10. Hastes de cotonete/pirulito",
        "11. Isqueiros",
        "12. Peda√ßos de isopor (maiores que 2,5 cm)",
        "13. Pinos de pl√°stico",
        "14. Sacos e sacolas",
        "15. Tampas/lacres/argolas de garrafa",
        "16. Outros (descreva)",

        # Borracha
        "Borracha (total)",
        "1. Bal√µes e bexigas",
        "2. C√¢maras de ar",
        "3. Chinelos/sand√°lias",
        "4. Luvas",
        "5. Pneus",
        "6. Preservativos (camisinha)",
        "7. Outros (descreva)",

        # Madeira
        "Madeira (total)",
        "1. Espetos/varas",
        "2. F√≥sforos",
        "3. Palitos de dente",
        "4. Palitos de sorvete/picol√©",
        "5. Peda√ßos de madeira",
        "6. Outros (descreva)",

        # Produtos t√™xteis
        "Produtos t√™xteis (total)",
        "1. Aviamentos (linhas/barbantes)",
        "2. Cal√ßados (sapatos, t√™nis)",
        "3. Roupas e peda√ßos de tecido",
        "4. Outros (descreva)",

        # Papel
        "Papel (total)",
        "1. Caixas de leite/suco, etc",
        "2. Embalagens de cigarro",
        "3. Embalagens de papel",
        "4. Jornais/panfletos/revistas/livros",
        "5. Papel√£o",
        "6. Peda√ßos de papel/guardanapos",
        "7. Outros (Descreva)2",

        # Metal
        "Metal (total)",
        "1. An√©is de lacre de latas de bebidas",
        "2. Latas de bebidas",
        "3. Latas (comida, desodorante, √≥leo, tinta, etc.)",
        "4. Peda√ßos de metal",
        "5. Tampas de metal",
        "6. Outros (descreva)2",

        # Vidro
        "Vidro (total)",
        "1. Copos/x√≠caras/pratos",
        "2. Garrafas",
        "3. L√¢mpadas",
        "4. Peda√ßos de cer√¢mica",
        "5. Peda√ßos de vidro",
        "6. Potes de vidro ou cer√¢mica",
        "7. Outros (descreva)3",

        # Materiais de Pesca
        "Materiais de Pesca (total)",
        "1. Anz√≥is",
        "2. Boias",
        "3. Linhas de pesca",
        "4. Peda√ßos de corda",
        "5. Redes/peda√ßos de rede",
        "6. Outros (descreva)5",

        # Outros res√≠duos
        "Outros Res√≠duos (total)",
        "1. Bitucas/guimbas/filtros de cigarro",
        "2. Cera de vela/parafina",
        "3. Eletroeletr√¥nicos (TV, celular, computador, etc.)",
        "4. Entulhos/material de constru√ß√£o",
        "5. Fraldas e absorventes",
        "6. Seringas",
        "7. Outros (descreva)6",

        # Animais
        "Animais",
        "Animais Vivos",
        "Animais Mortos",
    ]
]


df.loc[0, 'Institui√ß√£o Organizadora'] = 'Greenpeace Poa'

In [5]:
df2 = df2.rename(columns={'Cdigo UC':'Codigo UC',
                        'Informaes Gerais':'Informacoes Gerais',
                        'Ano de Criao':'Ano de Criacao',
                        'rgo Gestor':'Orgao Gestor',
                        'rea soma biomas':'Area soma biomas',
                        'rea soma Biomas Continental':'Area soma biomas continentais',
                        'Bioma rea (ha)':'Bioma area (ha)',
                        'Amaznia':'Amazonia',
                        'Mata Atlntica':'Mata Atlantica',
                        'rea Marinha':'Area Marinha',
                        'Municpio Costeiro':'Municipio Costeiro',
                        'Municpio Costeiro + rea Marinha':'Municipio Costeiro + Area Marinha',
                        'Municpios Abrangidos': 'Cidade', 'UF': 'Estado'})

df2 = df2[
    [
        # Identifica√ß√£o
        'ID_UC',
        'Codigo UC',
        'Informacoes Gerais',
        'Nome da UC',
        'Ano de Criacao',

        # Localiza√ß√£o
        'Cidade',
        'Estado',

        # Administra√ß√£o
        'Esfera Administrativa',
        'Categoria de Manejo',
        'Categoria IUCN',
        'Orgao Gestor',
        'Plano de Manejo',
        'Conselho Gestor',

        # √Årea e Bioma
        'Area soma biomas',
        'Area soma biomas continentais',
        'Area Marinha',
        'Bioma declarado', 

        # Outras caracter√≠sticas
        'Grupo',
        'Mar Territorial',
        'Municipio Costeiro',
        'Municipio Costeiro + Area Marinha',
        'Reserva da Biosfera'
    ]
]

df2['Cidade'] = df2['Cidade'].str.split(', ')
df2 = df2.explode('Cidade')
df2['Cidade'] = df2['Cidade'].str.replace(r'\([A-Z]{2}\)','', regex=True).str.strip()
df2['Estado'] = df2['Estado'].str.split(', ')
df2 = df2.explode('Estado')

# Tratamento e prepara√ß√£o dos DataFrames para a inser√ß√£o no banco de dados

### Tabela Tipo de Lixo

In [6]:
colunas_finais = [
    '1. Fragmentos de pl√°stico (maiores que 2,5 cm).',
    '3. Canudos',
    '5. Embalagens de alimento',
    '9. Garrafas PET',
    '14. Sacos e sacolas',
    '5. Pneus',
    '6. Preservativos (camisinha)',
    '2. Embalagens de cigarro',
    '4. Jornais/panfletos/revistas/livros',
    '3. Latas (comida, desodorante, √≥leo, tinta, etc.)',
    '4. Entulhos/material de constru√ß√£o',
    'Animais Mortos'
]

# Seleciona apenas as colunas finais
df_dados_coleta = df[colunas_finais].copy()

# Preenche valores ausentes com 0
df_dados_coleta.fillna(0, inplace=True)

# Adiciona coluna de ID
df_dados_coleta.insert(0, 'id_dados_coleta', range(1, len(df_dados_coleta) + 1))

df_dados_coleta = df_dados_coleta.rename(columns={'1. Fragmentos de pl√°stico (maiores que 2,5 cm).':'Fragmentos de pl√°stico',
                                                 '3. Canudos': 'Canudos',
                                                 '5. Embalagens de alimento': 'Embalagens de alimento',
                                                 '9. Garrafas PET':'Garrafas PET',
                                                 '14. Sacos e sacolas':'Sacolas',
                                                 '5. Pneus':'Pneus',
                                                 '6. Preservativos (camisinha)':'Preservativos',
                                                 '2. Embalagens de cigarro':'Embalagens de cigarro',
                                                 '4. Jornais/panfletos/revistas/livros':'Jornais/panfletos/revistas/livros',
                                                 '3. Latas (comida, desodorante, √≥leo, tinta, etc.)':'Latas',
                                                 '4. Entulhos/material de constru√ß√£o':'Entulhos'})

### Tabela Institui√ß√£o Organizadora

In [7]:
colunas = ['Institui√ß√£o Organizadora', 'Car√°ter da institui√ß√£o']

# Remove duplicatas e reinicia √≠ndice
df_instituicao_organizadora = df[colunas].drop_duplicates('Institui√ß√£o Organizadora').reset_index(drop=True)

# Adiciona coluna de ID
df_instituicao_organizadora.insert(0, 'id_instituicao_organizadora', range(1, len(df_instituicao_organizadora) + 1))

### Tabela Munic√≠pio

In [8]:
colunas_municipio = ['Cidade', 'Estado']

# Concatena e remove duplicatas
df_municipio = pd.concat([df[colunas_municipio], df2[colunas_municipio]])
df_municipio['Cidade'] = df_municipio['Cidade'].str.replace(r'\([A-Z]{2}\)', '', regex=True).str.strip()

# Remove duplicatas pela cidade e reinicia o √≠ndice
df_municipio = df_municipio.drop_duplicates('Cidade').reset_index(drop=True)

# Insere coluna de ID no in√≠cio
df_municipio.insert(0, 'id_municipio', range(1, len(df_municipio) + 1))

### Tabela Mutir√£o de Limpeza

In [9]:
df_mutirao = df[[
    'Data do mutir√£o',
    'Hor√°rio de in√≠cio',
    'N√∫mero aproximado de participantes (total)',
    'Dura√ß√£o total (coleta + triagem)',
    'Cidade',
    'Institui√ß√£o Organizadora'
]].copy()
df_mutirao.insert(0, 'id_mutirao', range(1, len(df_mutirao) + 1))

# Faz os merges encadeados
df_mutirao = (
    df_mutirao
    .merge(df_municipio[['id_municipio', 'Cidade']], on='Cidade', how='inner')
    .merge(df_instituicao_organizadora[['id_instituicao_organizadora', 'Institui√ß√£o Organizadora']], on='Institui√ß√£o Organizadora', how='inner')
)

# Seleciona e reordena as colunas finais
df_mutirao = df_mutirao[[
    'id_mutirao',
    'Data do mutir√£o',
    'Hor√°rio de in√≠cio',
    'N√∫mero aproximado de participantes (total)',
    'Dura√ß√£o total (coleta + triagem)',
    'id_municipio',
    'id_instituicao_organizadora'
]]

### Tabela Local de Coleta

In [10]:
# Seleciona a coluna relevante e adiciona o ID
df_local_coleta = df[['Nome do local (exemplo: praia de boa viagem)']].copy()
df_local_coleta.insert(0, 'id_local_coleta', range(1, len(df_local_coleta) + 1))

### Tabela Coleta de Lixo

In [11]:
# Seleciona as colunas relevantes e adiciona o ID
df_coleta_lixo = df[[
    'Pl√°stico (total)',
    'Borracha (total)',
    'Madeira (total)',
    'Produtos t√™xteis (total)',
    'Papel (total)',
    'Metal (total)',
    'Vidro (total)',
    'Materiais de Pesca (total)',
    'Outros Res√≠duos (total)'
]].copy()

# Adiciona a coluna de ID
df_coleta_lixo.insert(0, 'id_coleta_lixo', range(1, len(df_coleta_lixo) + 1))

### Tabela Esfera Administrativa

In [12]:
# Seleciona a coluna relevante, remove duplicados e adiciona o ID
df_esfera = df2[['Esfera Administrativa']].drop_duplicates().reset_index(drop=True)
df_esfera.insert(0, 'id_esfera', range(1, len(df_esfera) + 1))

### Tabela Categoria Manejo

In [13]:
# Seleciona as colunas relevantes, remove duplicados e adiciona o ID
df_manejo = df2[['Categoria de Manejo', 'Categoria IUCN', 'Plano de Manejo']].drop_duplicates(subset='Categoria de Manejo').reset_index(drop=True)

# Adiciona a coluna 'id_manejo' no in√≠cio
df_manejo.insert(0, 'id_manejo', range(1, len(df_manejo) + 1))

### Tabela Bioma

In [14]:
# Seleciona as colunas relevantes, remove duplicados e adiciona o ID
df_bioma = df2[['Bioma declarado']].drop_duplicates(subset='Bioma declarado').reset_index(drop=True)

# Adiciona a coluna 'id_bioma' no in√≠cio
df_bioma.insert(0, 'id_bioma', range(1, len(df_bioma) + 1))

### Tabela Unidade de Conserva√ß√£o

In [15]:
# Seleciona as colunas relevantes e remove duplicados baseados em 'Nome da UC'
df_uc = df2[['Nome da UC', 'Ano de Criacao', 'Esfera Administrativa',
             'Area soma biomas', 'Area soma biomas continentais',
             'Area Marinha', 'Bioma declarado', 'Cidade', 'Categoria de Manejo']].drop_duplicates('Nome da UC')

# Adiciona o ID da UC
df_uc.insert(0, 'id_uc', range(1, len(df_uc) + 1))

# Realiza os merges
df_uc = (df_uc
         .merge(df_bioma, on='Bioma declarado', how='inner')
         .merge(df_municipio, on='Cidade', how='inner')
         .merge(df_manejo, on='Categoria de Manejo', how='inner')
         .merge(df_esfera, on='Esfera Administrativa', how='inner'))

# Seleciona as colunas relevantes para o resultado final
df_uc = df_uc[['id_uc', 'Nome da UC', 'Ano de Criacao', 'Area soma biomas',
               'Area soma biomas continentais', 'Area Marinha', 'id_bioma',
               'id_municipio', 'id_manejo', 'id_esfera']]

# Converte as colunas de √°rea para o tipo num√©rico
df_uc[['Area soma biomas', 'Area soma biomas continentais', 'Area Marinha']] = (
    df_uc[['Area soma biomas', 'Area soma biomas continentais', 'Area Marinha']]
    .apply(pd.to_numeric, errors='coerce')
    .astype('float64')
)

## Importando SQL e Criando o Cursor para Execu√ß√£o de Queries: Adicione dbname e password conforme o seu Banco de Dados

In [1]:
import psycopg2 
from psycopg2 import sql
conn = psycopg2.connect(dbname = "", user = "postgres", password = "", host = "localhost", port = "5432")
cursor = conn.cursor()

## Criando as tabelas no Banco de Dados

In [ ]:
sql_criacao = '''
DROP TABLE IF EXISTS unidade_de_conservacao CASCADE;
DROP TABLE IF EXISTS categoria_manejo CASCADE;
DROP TABLE IF EXISTS bioma CASCADE;
DROP TABLE IF EXISTS tipo_de_lixo CASCADE;
DROP TABLE IF EXISTS local_de_coleta CASCADE;
DROP TABLE IF EXISTS instituicao_organizadora CASCADE;
DROP TABLE IF EXISTS municipio CASCADE;
DROP TABLE IF EXISTS esfera_administrativa CASCADE;
DROP TABLE IF EXISTS mutirao_de_limpeza CASCADE;
DROP TABLE IF EXISTS coleta_de_lixo CASCADE;


CREATE TABLE IF NOT EXISTS categoria_manejo (
    id_manejo INT PRIMARY KEY,
    categoria_de_manejo TEXT NOT NULL,
    categoria_iucn TEXT NOT NULL,
    plano_de_manejo TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS bioma (
    id_bioma INT PRIMARY KEY,
    bioma_declarado TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS municipio (
    id_municipio INT PRIMARY KEY,
    cidade TEXT NOT NULL,
    estado TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS esfera_administrativa (
    id_esfera INT PRIMARY KEY,
    esfera_administrativa TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS unidade_de_conservacao (
    id_uc INT PRIMARY KEY,
    nome_da_uc TEXT NOT NULL,
    ano_de_criacao INT,
    area_soma_biomas FLOAT,
    area_soma_biomas_continentais FLOAT,
    area_marinha FLOAT,
    id_bioma INT,
    id_municipio INT,
    id_manejo INT,
    id_esfera INT,
    FOREIGN KEY (id_manejo) REFERENCES categoria_manejo(id_manejo),
    FOREIGN KEY (id_bioma) REFERENCES bioma(id_bioma),
    FOREIGN KEY (id_municipio) REFERENCES municipio(id_municipio),
    FOREIGN KEY (id_esfera) REFERENCES esfera_administrativa(id_esfera)
);

CREATE TABLE IF NOT EXISTS instituicao_organizadora (
    id_instituicao_organizadora INT PRIMARY KEY,
    instituicao_organizadora TEXT NOT NULL,
    carater_da_instituicao TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS mutirao_de_limpeza (
    id_mutirao INT PRIMARY KEY,
    data_do_mutirao DATE NOT NULL,
    horario_de_inicio TIME NOT NULL,
    numero_aproximado_de_participantes INT,
    duracao_total TIME NOT NULL,
    id_municipio INT,
    id_instituicao_organizadora INT,
    FOREIGN KEY (id_municipio) REFERENCES municipio(id_municipio),
    FOREIGN KEY (id_instituicao_organizadora) REFERENCES instituicao_organizadora(id_instituicao_organizadora)
);

CREATE TABLE IF NOT EXISTS local_de_coleta (
    id_mutirao INT PRIMARY KEY,
    nome_do_local TEXT NOT NULL,
    FOREIGN KEY (id_mutirao) REFERENCES mutirao_de_limpeza(id_mutirao)
);

CREATE TABLE IF NOT EXISTS coleta_de_lixo (
    id_mutirao INT PRIMARY KEY,
    plastico INT,
    borracha INT,
    madeira INT,
    produtos_texteis INT,
    papel INT,
    metal INT,
    vidro INT,
    materiais_de_pesca INT,
    outros_residuos INT,
    FOREIGN KEY (id_mutirao) REFERENCES mutirao_de_limpeza(id_mutirao)
);

CREATE TABLE IF NOT EXISTS tipo_de_lixo (
    id_mutirao INT PRIMARY KEY,
    fragmentos_de_plastico INT,
    canudos INT,
    embalagens_de_alimento INT,
    garrafas_pet INT,
    sacolas INT, 
    pneus INT,
    preservativos INT,
    embalagens_de_cigarro INT,
    jornais_panfletos_revistas_livros INT,
    latas INT, entulhos INT, animais_mortos INT,
    FOREIGN KEY (id_mutirao) REFERENCES coleta_de_lixo(id_mutirao)
);
'''

cursor.execute(sql_criacao)

## Populando o Banco de Dados com os Dataframes

In [ ]:
for indice, linha in df_municipio.iterrows():
    cursor.execute(
        sql.SQL("""
            INSERT INTO municipio (id_municipio, cidade, estado)
            VALUES (%s, %s, %s)
        """),
        (linha['id_municipio'], linha['Cidade'], linha['Estado'])
    )

for indice, linha in df_instituicao_organizadora.iterrows():
    cursor.execute(
        sql.SQL("""
            INSERT INTO instituicao_organizadora (id_instituicao_organizadora, instituicao_organizadora, carater_da_instituicao)
            VALUES (%s, %s, %s)
        """),
        (linha['id_instituicao_organizadora'], linha['Institui√ß√£o Organizadora'], linha['Car√°ter da institui√ß√£o'])
    )

for indice, linha in df_mutirao.iterrows():
    cursor.execute(
        sql.SQL("""
            INSERT INTO mutirao_de_limpeza (id_mutirao, data_do_mutirao, horario_de_inicio, numero_aproximado_de_participantes,
            duracao_total, id_municipio, id_instituicao_organizadora)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """),  
        (linha['id_mutirao'], linha['Data do mutir√£o'], linha['Hor√°rio de in√≠cio'], linha['N√∫mero aproximado de participantes (total)'],
         linha['Dura√ß√£o total (coleta + triagem)'],linha['id_municipio'],linha['id_instituicao_organizadora'])
    )

for indice, linha in df_local_coleta.iterrows():
    cursor.execute(
        sql.SQL("""
            INSERT INTO local_de_coleta (id_mutirao, nome_do_local)
            VALUES (%s, %s)
        """),
        (linha['id_local_coleta'], linha['Nome do local (exemplo: praia de boa viagem)'])
    )

for indice, linha in df_esfera.iterrows():
    cursor.execute(
        sql.SQL("""
            INSERT INTO esfera_administrativa (id_esfera, esfera_administrativa)
            VALUES (%s, %s)
        """),
        (linha['id_esfera'], linha['Esfera Administrativa'])
    )

for indice, linha in df_coleta_lixo.iterrows():
    cursor.execute(
        sql.SQL("""
            INSERT INTO coleta_de_lixo (id_mutirao, plastico, borracha,
            madeira, produtos_texteis, papel, metal, vidro, materiais_de_pesca, outros_residuos)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """),
(int(linha['id_coleta_lixo']), int(linha['Pl√°stico (total)']), int(linha['Borracha (total)']), int(linha['Madeira (total)']),
 int(linha['Produtos t√™xteis (total)']), int(linha['Papel (total)']), int(linha['Metal (total)']), int(linha['Vidro (total)']),
 int(linha['Materiais de Pesca (total)']), int(linha['Outros Res√≠duos (total)']))
    )

for indice, linha in df_manejo.iterrows():
    cursor.execute(
        sql.SQL("""
            INSERT INTO categoria_manejo (id_manejo, categoria_de_manejo, categoria_iucn, plano_de_manejo)
            VALUES (%s, %s, %s, %s)
        """),
        (linha['id_manejo'], linha['Categoria de Manejo'], linha['Categoria IUCN'], linha['Plano de Manejo'])
    )

for indice, linha in df_bioma.iterrows():
    cursor.execute(
        sql.SQL("""
            INSERT INTO bioma (id_bioma, bioma_declarado)
            VALUES (%s, %s)
        """),
        (linha['id_bioma'], linha['Bioma declarado'])
    )

for indice, linha in df_uc.iterrows():
    cursor.execute(
        sql.SQL("""
            INSERT INTO unidade_de_conservacao (id_uc, nome_da_uc, ano_de_criacao, area_soma_biomas, area_soma_biomas_continentais, area_marinha,
            id_bioma, id_municipio, id_manejo, id_esfera)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """),
        (linha['id_uc'], linha['Nome da UC'], linha['Ano de Criacao'], linha['Area soma biomas'], linha['Area soma biomas continentais'], linha['Area Marinha'], 
         linha['id_bioma'], linha['id_municipio'], linha['id_manejo'], linha['id_esfera'])
    )

for indice, linha in df_dados_coleta.iterrows():
    cursor.execute(
        sql.SQL("""
            INSERT INTO tipo_de_lixo (id_mutirao, fragmentos_de_plastico, canudos, embalagens_de_alimento, garrafas_pet, sacolas, pneus,
            preservativos, embalagens_de_cigarro, jornais_panfletos_revistas_livros, latas, entulhos, animais_mortos)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """),
(int(linha['id_dados_coleta']), int(linha['Fragmentos de pl√°stico']), int(linha['Canudos']), int(linha['Embalagens de alimento']),
 int(linha['Garrafas PET']), int(linha['Sacolas']), int(linha['Pneus']), int(linha['Preservativos']), int(linha['Embalagens de cigarro']),
 int(linha['Jornais/panfletos/revistas/livros']), int(linha['Latas']), int(linha['Entulhos']), int(linha['Animais Mortos']))
    )

conn.commit()

## Query 1  -  Propor√ß√£o de Unidades de Conserva√ß√£o vs. Lixo Extra√≠do por Cidade em Mutir√µes de Limpeza

Esta query analisa a rela√ß√£o entre a presen√ßa de unidades de conserva√ß√£o ambiental e a quantidade de lixo coletado em mutir√µes de limpeza por cidade. O objetivo √© entender se √°reas com mais prote√ß√£o ambiental tendem a gerar menos res√≠duos ou se h√° outras correla√ß√µes relevantes.

In [ ]:
query_1 = '''
    SELECT
    	cidade, COUNT(nome_da_uc) AS qtd_uc, SUM(lixo_total) AS lixo_total_municipio
    FROM (
    	SELECT
    		"municipio".cidade,
    		"unidade_de_conservacao".nome_da_uc,
    		"mutirao_de_limpeza".id_municipio,
    		"mutirao_de_limpeza".id_mutirao,
    		(plastico + borracha + madeira + produtos_texteis + papel + 
    		 metal + vidro + materiais_de_pesca + outros_residuos) AS lixo_total
    	FROM
    		"coleta_de_lixo"
    	INNER JOIN "mutirao_de_limpeza" ON "coleta_de_lixo".id_mutirao = "mutirao_de_limpeza".id_mutirao
    	LEFT JOIN "unidade_de_conservacao" ON "mutirao_de_limpeza".id_municipio = "unidade_de_conservacao".id_municipio
    	INNER JOIN "municipio" ON "mutirao_de_limpeza".id_municipio = "municipio".id_municipio
    ) AS new_query
    GROUP BY cidade
    ORDER BY qtd_uc
'''
cursor.execute(query_1)
resultado = cursor.fetchall()
colunas = [desc[0] for desc in cursor.description]
query_1 = pd.DataFrame(resultado, columns=colunas)

## Query 2 - Propor√ß√£o de Lixo Extra√≠do vs. Unidades de Conserva√ß√£o por Estado

Esta query compara a quantidade de lixo coletado em mutir√µes de limpeza com o n√∫mero de unidades de conserva√ß√£o em cada estado. O objetivo √© identificar se estados com mais √°reas protegidas t√™m menor volume de res√≠duos ou se h√° padr√µes distintos na gera√ß√£o de lixo.

In [ ]:
query_2 = '''
    SELECT
    	estado, COUNT(nome_da_uc) AS qtd_uc, SUM(lixo_total) AS lixo_total_estado
    FROM (
    	SELECT
    		"coleta_de_lixo".id_mutirao,
    		"municipio".estado,
    		"unidade_de_conservacao".nome_da_uc,
    		"mutirao_de_limpeza".id_municipio,
    		"mutirao_de_limpeza".id_mutirao,
    		(plastico + borracha + madeira + produtos_texteis + papel + 
    		 metal + vidro + materiais_de_pesca + outros_residuos) AS lixo_total
    	FROM
    		"coleta_de_lixo"
    	INNER JOIN "mutirao_de_limpeza" ON "coleta_de_lixo".id_mutirao = "mutirao_de_limpeza".id_mutirao
    	LEFT JOIN "unidade_de_conservacao" ON "mutirao_de_limpeza".id_municipio = "unidade_de_conservacao".id_municipio
    	INNER JOIN "municipio" ON "mutirao_de_limpeza".id_municipio = "municipio".id_municipio
    ) AS new_query
    GROUP BY estado
    ORDER BY lixo_total_estado;
'''
cursor.execute(query_2)
resultado = cursor.fetchall()
colunas = [desc[0] for desc in cursor.description]
query_2 = pd.DataFrame(resultado, columns=colunas)

## Query 3 - An√°lise de Res√≠duos por Bioma em Mutir√µes de Limpeza

Esta query avalia a distribui√ß√£o de tipos e quantidades de lixo coletado em mutir√µes de limpeza, segmentado por biomas brasileiros. O objetivo √© identificar padr√µes de descarte e potencial impacto ambiental em diferentes ecossistemas.

In [ ]:
query_3 = '''
    SELECT (plastico_total + canudo_total + embalagens_de_alimento_total + garrafas_pet_total + sacolas_total + pneus_total +
	   preservativos_total + embalagens_de_cigarro_total + jornais_panfletos_revistas_livros_total +
	   latas_total + entulhos_total) AS qtd_lixo_total, *
    FROM(
    	SELECT b.bioma_declarado, COUNT(mcp.cidade) AS cidades_total, SUM(fragmentos_de_plastico) AS plastico_total, SUM(canudos) AS canudo_total,
    	       SUM(embalagens_de_alimento) AS embalagens_de_alimento_total, SUM(garrafas_pet) AS garrafas_pet_total,
    		   SUM(sacolas) AS sacolas_total, SUM(pneus) AS pneus_total, SUM(preservativos) AS preservativos_total, SUM(embalagens_de_cigarro) AS embalagens_de_cigarro_total,
    		   SUM(jornais_panfletos_revistas_livros) AS jornais_panfletos_revistas_livros_total, SUM(latas) AS latas_total, SUM(entulhos) AS entulhos_total
    	FROM "tipo_de_lixo" AS t
    	JOIN "mutirao_de_limpeza" AS m ON m.id_mutirao = t.id_mutirao
    	JOIN "unidade_de_conservacao" AS u ON u.id_municipio = m.id_municipio
    	JOIN "municipio" AS mcp ON mcp.id_municipio = m.id_municipio
    	JOIN "bioma" AS b ON b.id_bioma = u.id_bioma
    	GROUP BY bioma_declarado
    )
ORDER BY qtd_lixo_total
'''
cursor.execute(query_3)
resultado = cursor.fetchall()
colunas = [desc[0] for desc in cursor.description]
query_3 = pd.DataFrame(resultado, columns=colunas)

## Query 4 - Efici√™ncia das Institui√ß√µes Organizadoras por Natureza (P√∫blico vs. Privado)

Esta query avalia o desempenho de institui√ß√µes organizadoras de mutir√µes de limpeza, categorizadas por seu car√°ter (p√∫blico, privado, ONG, etc.), com base no volume total de res√≠duos coletados. O objetivo √© identificar quais tipos de organiza√ß√µes t√™m maior impacto nas a√ß√µes de limpeza.

In [ ]:
query_4 = '''
    SELECT carater_da_instituicao, COUNT(id_mutirao) AS qtd_mutiroes, SUM(lixo_total) AS lixo_total
    FROM(
    	SELECT
    		"instituicao_organizadora".carater_da_instituicao,
    		"municipio".cidade,
    		"mutirao_de_limpeza".id_municipio,
    		"mutirao_de_limpeza".id_mutirao,
    		(plastico + borracha + madeira + produtos_texteis + papel + 
    		 metal + vidro + materiais_de_pesca + outros_residuos) AS lixo_total
    	FROM
    		"coleta_de_lixo"
    	INNER JOIN "mutirao_de_limpeza" ON "coleta_de_lixo".id_mutirao = "mutirao_de_limpeza".id_mutirao
    	INNER JOIN "municipio" ON "mutirao_de_limpeza".id_municipio = "municipio".id_municipio
    	INNER JOIN "instituicao_organizadora" ON 
    		"instituicao_organizadora".id_instituicao_organizadora = "mutirao_de_limpeza".id_instituicao_organizadora
    )
    GROUP BY carater_da_instituicao
    ORDER BY lixo_total;
'''
cursor.execute(query_4)
resultado = cursor.fetchall()
colunas = [desc[0] for desc in cursor.description]
query_4 = pd.DataFrame(resultado, columns=colunas)

## Query 5 - An√°lise de Efici√™ncia dos Mutir√µes de Limpeza por Ano

Esta query avalia a efici√™ncia dos mutir√µes de limpeza em um ano espec√≠fico, com m√©tricas como:

- Volume total de res√≠duos coletados

- Produtividade por participante

- Intensidade da coleta (lixo por minuto)

- Comparativo entre meses/esta√ß√µes do ano

In [ ]:
query_5 = '''
    SELECT *, (lixo_total_ano/participantes_no_ano) AS lixo_extraido_por_pessoa, (lixo_total_ano/(EXTRACT(EPOCH FROM tempo_total_de_mutirao::INTERVAL)/60))
           AS lixo_extraido_por_minuto
    FROM(
    	SELECT EXTRACT(YEAR FROM data_do_mutirao) AS ano, SUM(numero_aproximado_de_participantes) AS participantes_no_ano, 
    		   SUM(duracao_total::INTERVAL) AS tempo_total_de_mutirao, COUNT(id_municipio) AS total_municipios, SUM(plastico) AS plastico_total,
    		   SUM(borracha) AS borracha_total, SUM(madeira) AS madeira_total, SUM(produtos_texteis) AS produtos_texteis_total,
    		   SUM(papel) AS papel_total, SUM(metal) AS metal, SUM(vidro) AS vidro_total, SUM(materiais_de_pesca) AS
    	       materiais_de_pesca_total, SUM(outros_residuos) AS outros_residuos_total, SUM(plastico + borracha + madeira + produtos_texteis
    		   + papel + metal + vidro + materiais_de_pesca + outros_residuos) AS lixo_total_ano
    	FROM "mutirao_de_limpeza" AS m
    	JOIN coleta_de_lixo AS c ON c.id_mutirao = m.id_mutirao 
    	GROUP BY ano
    	ORDER BY ano
    )
'''
cursor.execute(query_5)
resultado = cursor.fetchall()
colunas = [desc[0] for desc in cursor.description]
query_5 = pd.DataFrame(resultado, columns=colunas)